api_platform:
    title: ZKE Notes API
    version: 1.0.0
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
